### ISSUE TITLE
Extraer del material de Scrum los siguientes conceptos: Ceremonias, Artefactos y Roles

### ISSUE THREAD

**Issue by LuzGimenez** [Yanina-Unrein/Repositorio_Grupo2#1]

**Comment by Noeeelia** [comment]
Agrege lo basico. Alguno puede ampliar?. No se si es asi, je!

**Comment by Noeeelia** [comment]
Tuve algo de problemas para agregar al repo. Se escribia al reves nose que onda. A alguien mas le paso?
Me costo completar.
Tambien me escribia otras palabras.
