### ISSUE TITLE
Clonar el repositorio, crea su rama personal, moverse a ella y agregar su Curriculum Vitae (archivo formato .pdf) y subir la rama personal al repositorio

### ISSUE THREAD

**Issue by Yanina-Unrein** [Yanina-Unrein/Repositorio_Grupo2#3]
ETAPA 2 - Sprint 1     
Integrando los contenidos vistos con GitHub y, en esta oportunidad Git, utilizaremos esta consola de Git para realizar las siguientes tareas:
-Clonar el repositorio accediendo desde la rama principal en GitHub en la opción Code ->(HTTPS) en sus PC’s.
-Ya en sus discos locales, cada uno de los integrantes, crea su rama personal desde la consola de Git.
-Swichearse (moverse) a su rama personal.
-En la rama personal agregar su Curriculum Vitae (un archivo en formato .pdf) usando los comandos que hemos aprendido.
-Subir la rama personal al repositorio remoto.

**Comment by Noeeelia** [comment]
Hola Yani!! Como estas?
Consulto de donde sacaste toda esa info?.
Siento que no estoy al dia. Y que me falta ver un montón aún!!!
